[package]
name = "training"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "training"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { version="0.29.0", features = [ "init-if-needed" ] }
anchor-spl = { version="0.29.0", features = [ "metadata" ] }
seternia = { path = "./seternia"}
solana-program = "=1.17"
